#!/bin/sh

usage() {
  echo "Usage: $0 IP_RANGE_1.IP_RANGE_2.IP_RANGE_3.IP_RANGE_4"                          >&2
  echo                                                                                  >&2
  echo "Each octet range can be specified either as a range separated by a dash, or as" >&2
  echo "a single octet."                                                                >&2
  echo                                                                                  >&2
  echo "For example:"                                                                   >&2
  echo                                                                                  >&2
  echo "$0 10.0-10.0-255.0-255"                                                         >&2
  echo                                                                                  >&2
  echo "would scan all IP addresses from 10.0.0.0 to 10.10.255.255."                    >&2
  exit "$1"
}

parse() {
  eval "$(
    first_octet_range="$(echo "$1" | cut -d. -f1)"
    second_octet_range="$(echo "$1" | cut -d. -f2)"
    third_octet_range="$(echo "$1" | cut -d. -f3)"
    fourth_octet_range="$(echo "$1" | cut -d. -f4)"
    echo "export $2=$(echo "${first_octet_range}" | cut -d- -f1)"
    echo "export $3=$(echo "${first_octet_range}" | cut -d- -f2)"
    echo "export $4=$(echo "${second_octet_range}" | cut -d- -f1)"
    echo "export $5=$(echo "${second_octet_range}" | cut -d- -f2)"
    echo "export $6=$(echo "${third_octet_range}" | cut -d- -f1)"
    echo "export $7=$(echo "${third_octet_range}" | cut -d- -f2)"
    echo "export $8=$(echo "${fourth_octet_range}" | cut -d- -f1)"
    echo "export $9=$(echo "${fourth_octet_range}" | cut -d- -f2)"
  )"
  for var in 2 3 4 5 6 7 8 9
  do
    eval "$(
      innervar=$(eval echo "\$${var}")
      value=$(eval echo "\$${innervar}")
      case ${value}
      in
        (*[!0-9]*|'') echo usage 3 ;;
        (*)           if [ "${value}" -lt 0 ] || [ "${value}" -gt 255 ]
                      then
                        echo usage 2
                      fi ;;
      esac
    )"
  done
}

if [ "$#" -ne 1 ]
then
  usage 1
fi

parse "$1" ABEGIN AEND BBEGIN BEND CBEGIN CEND DBEGIN DEND
if  [ "${ABEGIN}" -gt "${AEND}" ] || \
    [ "${BBEGIN}" -gt "${BEND}" ] || \
    [ "${CBEGIN}" -gt "${CEND}" ] || \
    [ "${DBEGIN}" -gt "${DEND}" ]
then
  usage 4
fi

# echo "\$ABEGIN	=	$ABEGIN"
# echo "\$AEND  	=	$AEND"
# echo "\$BBEGIN	=	$BBEGIN"
# echo "\$BEND  	=	$BEND"
# echo "\$CBEGIN	=	$CBEGIN"
# echo "\$CEND  	=	$CEND"
# echo "\$DBEGIN	=	$DBEGIN"
# echo "\$DEND  	=	$DEND"

ABCCMD="for(i=${ABEGIN};i<=${AEND};i+=1) i"
BBCCMD="for(i=${BBEGIN};i<=${BEND};i+=1) i"
CBCCMD="for(i=${CBEGIN};i<=${CEND};i+=1) i"
DBCCMD="for(i=${DBEGIN};i<=${DEND};i+=1) i"

ALIST=$(echo "${ABCCMD}" | bc)
BLIST=$(echo "${BBCCMD}" | bc)
CLIST=$(echo "${CBCCMD}" | bc)
DLIST=$(echo "${DBCCMD}" | bc)

for A in ${ALIST}
do
  for B in ${BLIST}
  do
    for C in ${CLIST}
    do
      for D in ${DLIST}
      do
        IP="${A}.${B}.${C}.${D}"
        if [ "${#IP}" -le 7 ]
        then
          PAD="	"
        else
          PAD=""
        fi

        if ping -c 1 -W 0.01 "${IP}" 1>/dev/null 2>/dev/null
        then
          echo "${IP}	    present	${PAD}$(nslookup "${IP}" | \
            sed -e '/can.t find/s/^\*\* server can.t find //' \
                -e '/:/s/: /	nerr = /' \
                -e 's/^[0-9]*\.[0-9]*\.[0-9]*\.[0-9]*\.in-addr\.arpa	//g')"
        else
          echo "${IP}	${PAD}not present"
        fi
      done
    done
  done
done
